spring:
  application:
    name: WIMPServiceDiscovery

server:
  port: 8761

logging:
  config: classpath:logConfig.xml

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true